resolver: lts-14.1
extra-deps:
- git: https://github.com/masashi-y/optparse-declarative.git
  commit: a77c0e6917528e5fad83a4e03f98ea7727f103c8
flags: {}
extra-package-dbs: []
build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true
